/**
 * Represents a generic WebSocket envelope used for all events.
 * Each message carries an `action` describing the event and
 * an optional `payload` containing event-specific data.
 */
export interface IWebSocketEnvelope {
  /** Name of the WebSocket event (e.g., "chat-message", "join", "signal-offer"). */
  action: string;

  /** Optional data associated with the event. */
  payload?: any;
}

/**
 * Represents a chat message stored and transmitted through the system.
 */
export interface IMessage {
  /** Unique message ID (UUID generated by frontend or backend). */
  id: string;

  /** Room ID where the message was created. */
  roomId: string;

  /** ID of the user sending the message. */
  senderId: string;

  /** Type of message (e.g., "chat", "system", "signal"). */
  type: string;

  /** Text content of the message. */
  content: string;

  /** Timestamp in milliseconds (server-generated if missing). */
  timestamp: number;
}

/**
 * Strongly typed constants for socket event names.
 */
export const SocketEvents = {
  CONNECTION: "connection",
  DISCONNECT: "disconnect",
  JOIN_ROOM: "join_room",
  LEAVE_ROOM: "leave_room",
  NEW_MESSAGE: "new_message",
  MESSAGE_RECEIVED: "message_received",
  ROOM_USERS: "room_users"
} as const;

/**
 * Represents the union of all socket event names.
 */
export type SocketEventName = typeof SocketEvents[keyof typeof SocketEvents];

/**
 * Information about a user associated with a WebSocket connection.
 */
export interface UserPayload {
  /** Unique identifier of the user. */
  userId: string;

  /** Display name used in chat. */
  username: string;

  /** Room ID the user is currently connected to. */
  roomId: string;
}
